### ISSUE TITLE
Not possible to use it on 4.6

### ISSUE THREAD

**Issue by mbajur** [AlchemyCMS/alchemy-dragonfly-s3#3]
Hello!

It seems it's not possible to use that gem on `alchemy_cms 4.6`. The thing is, branch `alchemy-4` defines a following associaiton on `Picture` model:

https://github.com/AlchemyCMS/alchemy-dragonfly-s3/blob/alchemy-4/lib/alchemy/picture_monkey_patch.rb#L6

while there is no such model/table as `Alchemy::PictureThumb` on `4.6-stable` branch of `alchemy_cms`, it looks like it was introduced in `5.x`:

https://github.com/AlchemyCMS/alchemy_cms/tree/4.6-stable/app/models/alchemy

It all produces a following error when i'm trying to upload a picture:

```
ActiveRecord::StatementInvalid PG::UndefinedTable: ERROR:  relation "alchemy_picture_thumbs" does not exist
LINE 8:  WHERE a.attrelid = '"alchemy_picture_thumbs"'::regclass
                            ^
 in /Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `exec'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `block (2 levels) in query'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `block in query'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `query'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:820:in `column_definitions'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:114:in `columns'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/schema_cache.rb:76:in `columns'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/connection_adapters/schema_cache.rb:82:in `columns_hash'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:488:in `load_schema!'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/attributes.rb:247:in `load_schema!'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/attribute_decorators.rb:50:in `load_schema!'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:478:in `block in load_schema'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:475:in `synchronize'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:475:in `load_schema'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/model_schema.rb:352:in `columns_hash'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/core.rb:184:in `find_by'
/Users/mbajur/.rvm/gems/ruby-2.7.0/bundler/gems/alchemy-dragonfly-s3-a83d745dab79/app/models/alchemy/picture_thumb.rb:28:in `block in generate_thumbs!'
/Users/mbajur/.rvm/gems/ruby-2.7.0/bundler/gems/alchemy-dragonfly-s3-a83d745dab79/app/models/alchemy/picture_thumb.rb:22:in `map'
/Users/mbajur/.rvm/gems/ruby-2.7.0/bundler/gems/alchemy-dragonfly-s3-a83d745dab79/app/models/alchemy/picture_thumb.rb:22:in `generate_thumbs!'
/Users/mbajur/.rvm/gems/ruby-2.7.0/bundler/gems/alchemy-dragonfly-s3-a83d745dab79/lib/alchemy/picture_monkey_patch.rb:7:in `block in prepended'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:428:in `instance_exec'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:238:in `block in halting_and_conditional'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:517:in `block in invoke_after'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:517:in `each'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:517:in `invoke_after'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:136:in `run_callbacks'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:825:in `_run_create_callbacks'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/callbacks.rb:331:in `_create_record'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/timestamp.rb:110:in `_create_record'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:905:in `create_or_update'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/callbacks.rb:327:in `block in create_or_update'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activesupport-6.0.3.4/lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/callbacks.rb:327:in `create_or_update'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/timestamp.rb:128:in `create_or_update'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/persistence.rb:470:in `save'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/validations.rb:47:in `save'
/Users/mbajur/.rvm/gems/ruby-2.7.0/gems/activerecord-6.0.3.4/lib/active_record/transactions.rb:314:in `block in save'
```

**Comment by tvdeyen** [comment]
The migration is included in this Gem. Please run

```
bin/rake alchemy_dragonfly_s3:install:migrations
```

**Comment by tvdeyen** [comment]
As you can also see in the README of the `alchemy-4` branch

https://github.com/AlchemyCMS/alchemy-dragonfly-s3/tree/alchemy-4#installation
